title: PIQP
description: An embedded Proximal Interior Point Quadratic Programming solver
theme: just-the-docs
color_scheme: piqp

permalink: /:categories/:title
url: https://github.com/PREDICT-EPFL/piqp

aux_links:
  Github: https://github.com/PREDICT-EPFL/piqp
aux_links_new_tab: true

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/PREDICT-EPFL/piqp" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

callouts:
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: yellow
